// Generated by gencpp from file sticky_fingers/StickyControlRequest.msg
// DO NOT EDIT!


#ifndef STICKY_FINGERS_MESSAGE_STICKYCONTROLREQUEST_H
#define STICKY_FINGERS_MESSAGE_STICKYCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sticky_fingers
{
template <class ContainerAllocator>
struct StickyControlRequest_
{
  typedef StickyControlRequest_<ContainerAllocator> Type;

  StickyControlRequest_()
    : sticky_status(false)  {
    }
  StickyControlRequest_(const ContainerAllocator& _alloc)
    : sticky_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _sticky_status_type;
  _sticky_status_type sticky_status;




  typedef boost::shared_ptr< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StickyControlRequest_

typedef ::sticky_fingers::StickyControlRequest_<std::allocator<void> > StickyControlRequest;

typedef boost::shared_ptr< ::sticky_fingers::StickyControlRequest > StickyControlRequestPtr;
typedef boost::shared_ptr< ::sticky_fingers::StickyControlRequest const> StickyControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sticky_fingers::StickyControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sticky_fingers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17569b20c47f1b16fde3bc2cc84fc9dc";
  }

  static const char* value(const ::sticky_fingers::StickyControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17569b20c47f1b16ULL;
  static const uint64_t static_value2 = 0xfde3bc2cc84fc9dcULL;
};

template<class ContainerAllocator>
struct DataType< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sticky_fingers/StickyControlRequest";
  }

  static const char* value(const ::sticky_fingers::StickyControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
bool sticky_status\n\
";
  }

  static const char* value(const ::sticky_fingers::StickyControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sticky_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StickyControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sticky_fingers::StickyControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sticky_fingers::StickyControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "sticky_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sticky_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STICKY_FINGERS_MESSAGE_STICKYCONTROLREQUEST_H
