// Generated by gencpp from file new_action_server/newGoal.msg
// DO NOT EDIT!


#ifndef NEW_ACTION_SERVER_MESSAGE_NEWGOAL_H
#define NEW_ACTION_SERVER_MESSAGE_NEWGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_action_server
{
template <class ContainerAllocator>
struct newGoal_
{
  typedef newGoal_<ContainerAllocator> Type;

  newGoal_()
    : x(0)
    , y(0)
    , z(0)
    , a(0)  {
    }
  newGoal_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)
    , a(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _z_type;
  _z_type z;

   typedef int32_t _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::new_action_server::newGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_action_server::newGoal_<ContainerAllocator> const> ConstPtr;

}; // struct newGoal_

typedef ::new_action_server::newGoal_<std::allocator<void> > newGoal;

typedef boost::shared_ptr< ::new_action_server::newGoal > newGoalPtr;
typedef boost::shared_ptr< ::new_action_server::newGoal const> newGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_action_server::newGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_action_server::newGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace new_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'new_action_server': ['/home/brucemingxinliu/ros_ws/devel/share/new_action_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::new_action_server::newGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_action_server::newGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_action_server::newGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_action_server::newGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_action_server::newGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_action_server::newGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_action_server::newGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5f6b18e85d0edc6d39116c33e44ac7c";
  }

  static const char* value(const ::new_action_server::newGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5f6b18e85d0edc6ULL;
  static const uint64_t static_value2 = 0xd39116c33e44ac7cULL;
};

template<class ContainerAllocator>
struct DataType< ::new_action_server::newGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_action_server/newGoal";
  }

  static const char* value(const ::new_action_server::newGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_action_server::newGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
#goal:\n\
\n\
\n\
\n\
int32 x\n\
int32 y\n\
int32 z\n\
int32 a\n\
";
  }

  static const char* value(const ::new_action_server::newGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_action_server::newGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_action_server::newGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_action_server::newGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_ACTION_SERVER_MESSAGE_NEWGOAL_H
