// Generated by gencpp from file new_action_server/newResult.msg
// DO NOT EDIT!


#ifndef NEW_ACTION_SERVER_MESSAGE_NEWRESULT_H
#define NEW_ACTION_SERVER_MESSAGE_NEWRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_action_server
{
template <class ContainerAllocator>
struct newResult_
{
  typedef newResult_<ContainerAllocator> Type;

  newResult_()
    : return_code(0)  {
    }
  newResult_(const ContainerAllocator& _alloc)
    : return_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _return_code_type;
  _return_code_type return_code;




  typedef boost::shared_ptr< ::new_action_server::newResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_action_server::newResult_<ContainerAllocator> const> ConstPtr;

}; // struct newResult_

typedef ::new_action_server::newResult_<std::allocator<void> > newResult;

typedef boost::shared_ptr< ::new_action_server::newResult > newResultPtr;
typedef boost::shared_ptr< ::new_action_server::newResult const> newResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_action_server::newResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_action_server::newResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace new_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'new_action_server': ['/home/brucemingxinliu/ros_ws/devel/share/new_action_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::new_action_server::newResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_action_server::newResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_action_server::newResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_action_server::newResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_action_server::newResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_action_server::newResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_action_server::newResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c285fc637ab43abc6f59f97aab55a3bb";
  }

  static const char* value(const ::new_action_server::newResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc285fc637ab43abcULL;
  static const uint64_t static_value2 = 0x6f59f97aab55a3bbULL;
};

template<class ContainerAllocator>
struct DataType< ::new_action_server::newResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_action_server/newResult";
  }

  static const char* value(const ::new_action_server::newResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_action_server::newResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
\n\
\n\
int32 return_code\n\
";
  }

  static const char* value(const ::new_action_server::newResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_action_server::newResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_action_server::newResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_action_server::newResult_<ContainerAllocator>& v)
  {
    s << indent << "return_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.return_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_ACTION_SERVER_MESSAGE_NEWRESULT_H
