// Generated by gencpp from file seekthermal_ros/ThermalImage.msg
// DO NOT EDIT!


#ifndef SEEKTHERMAL_ROS_MESSAGE_THERMALIMAGE_H
#define SEEKTHERMAL_ROS_MESSAGE_THERMALIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace seekthermal_ros
{
template <class ContainerAllocator>
struct ThermalImage_
{
  typedef ThermalImage_<ContainerAllocator> Type;

  ThermalImage_()
    : height(0)
    , width(0)
    , data_raw()
    , data_mask()
    , image_gray()
    , image_colored()  {
    }
  ThermalImage_(const ContainerAllocator& _alloc)
    : height(0)
    , width(0)
    , data_raw(_alloc)
    , data_mask(_alloc)
    , image_gray(_alloc)
    , image_colored(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _width_type;
  _width_type width;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_raw_type;
  _data_raw_type data_raw;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_mask_type;
  _data_mask_type data_mask;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_gray_type;
  _image_gray_type image_gray;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_colored_type;
  _image_colored_type image_colored;




  typedef boost::shared_ptr< ::seekthermal_ros::ThermalImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seekthermal_ros::ThermalImage_<ContainerAllocator> const> ConstPtr;

}; // struct ThermalImage_

typedef ::seekthermal_ros::ThermalImage_<std::allocator<void> > ThermalImage;

typedef boost::shared_ptr< ::seekthermal_ros::ThermalImage > ThermalImagePtr;
typedef boost::shared_ptr< ::seekthermal_ros::ThermalImage const> ThermalImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seekthermal_ros::ThermalImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seekthermal_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'seekthermal_ros': ['/home/brucemingxinliu/ros_ws/src/seekthermal_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seekthermal_ros::ThermalImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seekthermal_ros::ThermalImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seekthermal_ros::ThermalImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9608fc0145356b4c079fd63bb3bd179c";
  }

  static const char* value(const ::seekthermal_ros::ThermalImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9608fc0145356b4cULL;
  static const uint64_t static_value2 = 0x079fd63bb3bd179cULL;
};

template<class ContainerAllocator>
struct DataType< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seekthermal_ros/ThermalImage";
  }

  static const char* value(const ::seekthermal_ros::ThermalImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 height\n\
uint32 width\n\
\n\
# float32 image, raw data\n\
float32[] data_raw # actual matrix data, size is (height*width) col1, col2, ...\n\
\n\
# uint8 image, dead pixel mask\n\
uint8[] data_mask # actual matrix data, size is (height*width) col1, col2, ...\n\
\n\
# images\n\
sensor_msgs/Image image_gray\n\
sensor_msgs/Image image_colored\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seekthermal_ros::ThermalImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.data_raw);
      stream.next(m.data_mask);
      stream.next(m.image_gray);
      stream.next(m.image_colored);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThermalImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seekthermal_ros::ThermalImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seekthermal_ros::ThermalImage_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "data_raw[]" << std::endl;
    for (size_t i = 0; i < v.data_raw.size(); ++i)
    {
      s << indent << "  data_raw[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data_raw[i]);
    }
    s << indent << "data_mask[]" << std::endl;
    for (size_t i = 0; i < v.data_mask.size(); ++i)
    {
      s << indent << "  data_mask[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data_mask[i]);
    }
    s << indent << "image_gray: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_gray);
    s << indent << "image_colored: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_colored);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEEKTHERMAL_ROS_MESSAGE_THERMALIMAGE_H
