; Auto-generated. Do not edit!


(cl:in-package new_action_server-msg)


;//! \htmlinclude newFeedback.msg.html

(cl:defclass <newFeedback> (roslisp-msg-protocol:ros-message)
  ((fdbk
    :reader fdbk
    :initarg :fdbk
    :type cl:integer
    :initform 0))
)

(cl:defclass newFeedback (<newFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <newFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'newFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name new_action_server-msg:<newFeedback> is deprecated: use new_action_server-msg:newFeedback instead.")))

(cl:ensure-generic-function 'fdbk-val :lambda-list '(m))
(cl:defmethod fdbk-val ((m <newFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader new_action_server-msg:fdbk-val is deprecated.  Use new_action_server-msg:fdbk instead.")
  (fdbk m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <newFeedback>) ostream)
  "Serializes a message object of type '<newFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'fdbk)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <newFeedback>) istream)
  "Deserializes a message object of type '<newFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'fdbk) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<newFeedback>)))
  "Returns string type for a message object of type '<newFeedback>"
  "new_action_server/newFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'newFeedback)))
  "Returns string type for a message object of type 'newFeedback"
  "new_action_server/newFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<newFeedback>)))
  "Returns md5sum for a message object of type '<newFeedback>"
  "46cc8f8da6ebf35aedc6bad2e96b2e59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'newFeedback)))
  "Returns md5sum for a message object of type 'newFeedback"
  "46cc8f8da6ebf35aedc6bad2e96b2e59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<newFeedback>)))
  "Returns full string definition for message of type '<newFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback: optional; ~%int32 fdbk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'newFeedback)))
  "Returns full string definition for message of type 'newFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback: optional; ~%int32 fdbk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <newFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <newFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'newFeedback
    (cl:cons ':fdbk (fdbk msg))
))
